name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir dist && echo "hello world" > dist/output.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build
      - run: cat ./build/output.txt
